### ISSUE TITLE
Create DB script logs error

### ISSUE THREAD

**Issue by lumodon** [LearnersGuild/idm#215] opened 2017-09-25 19:23 UTC
When onboarding new members, confusion is created by the error reported from running `npm run db:create` - the error is just a message about dropping database, but everything actually runs fine. Instead of including in the readme a note about ignoring this error, we should remove the error message since everything actually works.

**Comment by prattsj** [comment] 2017-09-28 17:45
Thanks, @lumodon. Duplicate of https://github.com/LearnersGuild/idm/issues/170.

**Closed by prattsj** 2017-09-28 17:45 UTC
